---
- name: Install packages for logshipping to logstash
  win_chocolatey:
    name: '{{ item }}'
    state: "{{ (logshipping_required|default(True) == True) | ternary('present', 'absent') }}"
    install_args: '-y'
  with_items: 
     - filebeat
     - winlogbeat
  tags: ['install']

