---
- name: Include generic variable for an OS distribution
  include_vars: '{{ item }}'
  with_first_found:
  - '{{ ansible_distribution }}.yml'
  - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
  - default_distro.yml
  tags: ['logshipping']

- name: Include generic variables for a group of hosts
  include_vars: '{{ item }}'
  with_first_found:
  - '{{ ansible_limit }}.yml'
  - default_group.yml
  tags: ['logshipping']

- name: Include variables for a particular host
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ inventory_hostname }}.yml'
    - default_host.yml
  tags: ['logshipping']

- name: Install logshipping
  include_tasks: install.yml
  when:
    - ansible_facts['os_family']|lower == "windows"
  tags: ['logshipping']

- name: Configure logshipping
  include_tasks: setup.yml
  when: >
    ansible_facts['os_family']|lower == "windows" and
    logshipping_required|default(True) == True
  tags: ['logshipping']

- name: Manage logshipping services
  include_tasks: services.yml
  when: >
    ansible_facts['os_family']|lower == "windows" and
    logshipping_required|default(True) == True
  tags: ['logshipping']
