---
- name: Install AIDE (Advanced Intrusion Detection Environment)
  block: 

    - name: Ensure AIDE HIDS is installed
      package:
        name: aide
        state: present
      notify: initialize_AIDE_database

    - name: Check whether the stock AIDE Database exists
      stat:
        path: /var/lib/aide/aide.db.new.gz
      register: aide_database_stat

    - name: Stage AIDE Database
      copy:
        src: /var/lib/aide/aide.db.new.gz
        dest: /var/lib/aide/aide.db.gz
        backup: true
        remote_src: true
      when:
        - (aide_database_stat.stat.exists is defined and aide_database_stat.stat.exists)

    - name: Generate aide configuration file
      copy:
        src: '../conf/aide.conf.debian'
        dest: '/etc/aide/aide.conf'
        owner: root
        group: root
        mode: '0644'
      when:
        - ansible_facts['os_family']|lower == "debian"
      notify: restart_auditd

    - name: Configure Periodic Execution of AIDE
      cron:
        name: run AIDE check
        minute: '15'
        hour: '13'
        weekday: '5'
        user: 'root'
        job: /usr/bin/aide --config /etc/aide/aide.conf --check | mail -s "AIDE report" {{ vault_linux_admin_user }}

  tags: ['install']


