---
- name: Include variables
  include_vars: '{{ item }}'
  with_first_found:
  - "{{ ansible_distribution }}.yml"
  - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  - default_distro.yml
  tags:
   - compliance
   - scap

- name: Include particular variables for the inventory group
  include_vars: '{{ item }}'
  with_first_found:
  - '{{ ansible_limit }}.yml'
  - default_group.yml
  tags:
   - compliance
   - scap

- name: Include variables particulares para el host
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ inventory_hostname }}.yml'
    - default_host.yml
  tags:
   - compliance
   - scap

- name: Hardening policies for software
  include_tasks: packages.yml
  tags:
   - compliance
   - scap

- name: Hardening policies for services
  include_tasks: services.yml
  tags:
   - compliance
   - scap

- name: Hardening configuration policies
  include_tasks: settings.yml
  tags:
   - compliance
   - scap
