---
packages_present:
  - libopenscap8
  - ssg-base
  - ssg-debderived
  - ssg-debian
  - ssg-nondebian
  - ssg-applications
  - libpam-runtime
  - libpam-cracklib
  - libpam-pwquality
  - libpwquality-tools
  - auditd
  - rsyslog
  - cron
  - debsums
  - apt-show-versions

packages_absent:
  - nis
  - avahi-daemon
  - telnet
  - telnetd
  - telnetd-ssl
  - inetutils-telnetd
  - ntpdate
  - chrony

services_running:
  - auditd
  - rsyslog
  - cron
  - ufw
  #- systemd-timesyncd # service masked
  - sshd

services_stopped:
  - ntp
  - cups
  - apport.service

scap_guides_version: '0.1.60'
scap_guides_folder: '/usr/share/xml/scap'

ssh_simmetric_ciphers: 'aes128-ctr,aes192-ctr,aes256-ctr'
ssh_mac_ciphers: 'hmac-sha2-256,hmac-sha2-512'
ssh_hostkey_ciphers: 'ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-rsa,ssh-dss'
ssh_kex_ciphers: 'ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256'
ssh_clientalivecountmax: 0
ssh_clientaliveinterval: 300 
ssh_maxauthtries: 6
ssh_maxsessions: 2
ssh_loglevel: 'INFO'

var_sudo_logfile: '/var/log/sudo.log'

grub2_conf_file: '/etc/default/grub'

minlen: 14
lcredit: -1
ucredit: -1
dcredit: -1
ocredit: -1
difok: 5
retry: 3
minclass: 4
pwd_remember: 5
pwd_max_days: 99999
pwd_min_days: 1
pwd_warn_age: 7
max_failed_login_attempts: 10 
unlock_timeout: 300 
user_inactivity: 30
default_umask: '027'

file_environment: '/etc/environment'
histfilesize: 30
histsize: 30
session_timeout: 600
