---
# No aplicable a workstations de planta
- name: "19.1.3.1,CCE-37970-1 | Ensure 'Enable screen saver' is set to {{ (screensaver_enabled|default(True) == True ) | ternary('Enabled', 'Disabled') }}"
  win_regedit:
     path: HKU:\.DEFAULT\Software\Policies\Microsoft\Windows\Control Panel\Desktop
     name: "ScreenSaveActive"
     data: "{{ (screensaver_enabled|default(True) == True ) | ternary('1', '0') }}"
     type: string
  when: >
      ansible_virtualization_role != "guest" and
      ansible_system_vendor != "QEMU"
  tags: ['configuration']

# No aplicable a workstations de planta
- name: "19.1.3.1,CCE-37970-1 | Ensure 'Enable screen saver' is set to {{ (screensaver_enabled|default(True) == True ) | ternary('Enabled', 'Disabled') }}"
  win_regedit:
     path: HKCU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop
     name: "ScreenSaveActive"
     data: "{{ (screensaver_enabled|default(True) == True ) | ternary('1', '0') }}"
     type: string
  when: >
      ansible_virtualization_role != "guest" and
      ansible_system_vendor != "QEMU"
  tags: ['configuration']

# No aplicable a workstations de planta
- name: "19.1.3.2,CCE-37907-3 | Ensure 'Force specific screen saver - Screen saver executable name' is set to 'Enabled - scrnsave.scr'"
  win_regedit:
     path: HKU:\.DEFAULT\Software\Policies\Microsoft\Windows\Control Panel\Desktop
     name: "SCRNSAVE.EXE"
     data: "scrnsave.scr"
     type: string
  when: >
      ansible_virtualization_role != "guest" and
      ansible_system_vendor != "QEMU" and
      (screensaver_enabled|default(True) == True)
  tags: ['configuration']

# No aplicable a workstations de planta
- name: "19.1.3.2,CCE-37907-3 | Ensure 'Force specific screen saver - Screen saver executable name' is set to 'Enabled - scrnsave.scr'"
  win_regedit:
     path: HKCU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop
     name: "SCRNSAVE.EXE"
     data: "scrnsave.scr"
     type: string
  when: >
      ansible_virtualization_role != "guest" and
      ansible_system_vendor != "QEMU" and
      (screensaver_enabled|default(True) == True)
  tags: ['configuration']

# No aplicable a workstations de planta
- name: "19.1.3.3,CCE-37658-2 | Ensure 'Password protect the screen saver' is set to {{ (screensaver_enabled|default(True) == True ) | ternary('Enabled', 'Disabled') }}"
  win_regedit:
     path: HKCU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop
     name: "ScreenSaverIsSecure"
     data: "{{ (screensaver_enabled|default(True) == True ) | ternary('1', '0') }}"
     type: string
  when: >
      ansible_virtualization_role != "guest" and
      ansible_system_vendor != "QEMU"
  tags: ['configuration']

# No aplicable a workstations de planta
- name: "19.1.3.4,CCE-37908-1 | Ensure 'Screen saver timeout' is set to 'Enabled - 900 seconds or fewer, but not 0'"
  win_regedit:
     path: HKU:\.DEFAULT\Software\Policies\Microsoft\Windows\Control Panel\Desktop
     name: "ScreenSaveTimeOut"
     data: "900"
     type: string
  when: >
      ansible_virtualization_role != "guest" and
      ansible_system_vendor != "QEMU" and
      (screensaver_enabled|default(True) == True)
  tags: ['configuration']

# No aplicable a workstations de planta
- name: "19.1.3.4,CCE-37908-1 | Ensure 'Screen saver timeout' is set to 'Enabled - 900 seconds or fewer, but not 0'"
  win_regedit:
     path: HKCU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop
     name: "ScreenSaveTimeOut"
     data: "900"
     type: string
  when: >
      ansible_virtualization_role != "guest" and
      ansible_system_vendor != "QEMU" and
      (screensaver_enabled|default(True) == True)
  tags: ['configuration']

# No aplicable a workstations de planta
- name: "19.5.1.1,CCE-36332-5 | Ensure 'Turn off toast notifications on the lock screen' is set to {{ (screensaver_enabled|default(True) == True ) | ternary('Enabled', 'Disabled') }}"
  win_regedit:
     path: HKU:\.DEFAULT\Software\Policies\Microsoft\Windows\Currentversion\Pushnotifications
     name: "NoToastApplicationNotificationOnLockScreen"
     data: "{{ (screensaver_enabled|default(True) == True ) | ternary('1', '0') }}"
     type: dword
  when: >
      ansible_virtualization_role != "guest" and
      ansible_system_vendor != "QEMU"
  tags: ['configuration']

# No aplicable a workstations de planta
- name: "19.5.1.1,CCE-36332-5 | Ensure 'Turn off toast notifications on the lock screen' is set to {{ (screensaver_enabled|default(True) == True ) | ternary('Enabled', 'Disabled') }}"
  win_regedit:
     path: HKCU:\Software\Policies\Microsoft\Windows\Currentversion\Pushnotifications
     name: "NoToastApplicationNotificationOnLockScreen"
     data: "{{ (screensaver_enabled|default(True) == True ) | ternary('1', '0') }}"
     type: dword
  when: >
      ansible_virtualization_role != "guest" and
      ansible_system_vendor != "QEMU"
  tags: ['configuration']

- name: "19.7.4.1,CCE-37424-9 | Ensure 'Do not preserve zone information in file attachments' is set to 'Disabled'"
  win_regedit:
     path: HKU:\.DEFAULT\Software\Microsoft\Windows\Currentversion\Policies\Attachments
     name: "SaveZoneInformation"
     data: "2"
     type: dword
  tags: ['configuration']

- name: "19.7.4.1,CCE-37424-9 | Ensure 'Do not preserve zone information in file attachments' is set to 'Disabled'"
  win_regedit:
     path: HKCU:\Software\Microsoft\Windows\Currentversion\Policies\Attachments
     name: "SaveZoneInformation"
     data: "2"
     type: dword
  tags: ['configuration']

- name: "19.7.4.2,CCE-36622-9 | Ensure 'Notify antivirus programs when opening attachments' is set to 'Enabled'"
  win_regedit:
     path: HKU:\.DEFAULT\Software\Microsoft\Windows\Currentversion\Policies\Attachments
     name: "ScanWithAntiVirus"
     data: "3"
     type: dword
  tags: ['configuration']

- name: "19.7.4.2,CCE-36622-9 | Ensure 'Notify antivirus programs when opening attachments' is set to 'Enabled'"
  win_regedit:
     path: HKCU:\Software\Microsoft\Windows\Currentversion\Policies\Attachments
     name: "ScanWithAntiVirus"
     data: "3"
     type: dword
  tags: ['configuration']

- name: "19.7.7.2,CCE-Null | Ensure 'Do not suggest third-party content in Windows spotlight' is set to 'Enabled'"
  win_regedit:
     path: HKU:\.DEFAULT\Software\Policies\Microsoft\Windows\CloudContent
     name: "DisableThirdPartySuggestions"
     data: "1"
     type: dword
  tags: ['configuration']

- name: "19.7.7.2,CCE-Null | Ensure 'Do not suggest third-party content in Windows spotlight' is set to 'Enabled'"
  win_regedit:
     path: HKCU:\Software\Policies\Microsoft\Windows\CloudContent
     name: "DisableThirdPartySuggestions"
     data: "1"
     type: dword
  tags: ['configuration']

- name: "19.7.26.1,CCE-38070-9 | Ensure 'Prevent users from sharing files within their profile.' is set to 'Enabled'"
  win_regedit:
     path: HKU:\.DEFAULT\Software\Microsoft\Windows\Currentversion\Policies\Explorer
     name: "NoInplaceSharing"
     data: "1"
     type: dword
  tags: ['configuration']

- name: "19.7.26.1,CCE-38070-9 | Ensure 'Prevent users from sharing files within their profile.' is set to 'Enabled'"
  win_regedit:
     path: HKCU:\Software\Microsoft\Windows\Currentversion\Policies\Explorer
     name: "NoInplaceSharing"
     data: "1"
     type: dword
  tags: ['configuration']

- name: "19.7.39.1,CCE-37490-0 | Ensure 'Always install with elevated privileges' is set to 'Disabled'"
  win_regedit:
     path: HKU:\.DEFAULT\Software\Policies\Microsoft\Windows\Installer
     name: "AlwaysInstallElevated"
     data: "0"
     type: dword
  tags: ['configuration']

- name: "19.7.39.1,CCE-37490-0 | Ensure 'Always install with elevated privileges' is set to 'Disabled'"
  win_regedit:
     path: HKCU:\Software\Policies\Microsoft\Windows\Installer
     name: "AlwaysInstallElevated"
     data: "0"
     type: dword
  tags: ['configuration']

- name: "19.6.5.1.1,CCE-37542-8 | Ensure 'Turn off Help Experience Improvement Program' is set to 'Enabled'"
  win_regedit:
     path: HKU:\.DEFAULT\Software\Policies\Microsoft\Assistance\Client\1.0
     name: "NoImplicitFeedback"
     data: "1"
     type: dword
  tags: ['configuration']

- name: "19.6.5.1.1,CCE-37542-8 | Ensure 'Turn off Help Experience Improvement Program' is set to 'Enabled'"
  win_regedit:
     path: HKCU:\Software\Policies\Microsoft\Assistance\Client\1.0
     name: "NoImplicitFeedback"
     data: "1"
     type: dword
  tags: ['configuration']

- name: "19.7.7.1,CCE-Null | Ensure 'Configure Windows spotlight on Lock Screen' is set to Disabled'"
  win_regedit:
     path: HKU:\.DEFAULT\Software\Policies\Microsoft\Windows\CloudContent
     name: "ConfigureWindowsSpotlight"
     data: "2"
     type: dword
  tags: ['configuration']

- name: "19.7.7.1,CCE-Null | Ensure 'Configure Windows spotlight on Lock Screen' is set to Disabled'"
  win_regedit:
     path: HKCU:\Software\Policies\Microsoft\Windows\CloudContent
     name: "ConfigureWindowsSpotlight"
     data: "2"
     type: dword
  tags: ['configuration']

- name: "19.7.43.2.1,CCE-37445-4 | Ensure 'Prevent Codec Download' is set to 'Enabled'"
  win_regedit:
     path: HKU:\.DEFAULT\Software\Policies\Microsoft\Windowsmediaplayer
     name: "PreventCodecDownload"
     data: "1"
     type: dword
  tags: ['configuration']

- name: "19.7.43.2.1,CCE-37445-4 | Ensure 'Prevent Codec Download' is set to 'Enabled'"
  win_regedit:
     path: HKCU:\Software\Policies\Microsoft\Windowsmediaplayer
     name: "PreventCodecDownload"
     data: "1"
     type: dword
  tags: ['configuration']
