---
- name: Configure System Event Log (Application) | windows-audit-100
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\EventLog\Application
    name: "MaxSize"
    data: "1"
    type: dword
  tags: ['configuration']

- name: Configure System Event Log (Security) | windows-audit-101
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\EventLog\Security
    name: "MaxSize"
    data: "1"
    type: dword
  tags: ['configuration']

- name: Configure System Event Log (Setup) | windows-audit-102
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\EventLog\Setup
    name: "MaxSize"
    data: "1"
    type: dword
  tags: ['configuration']

- name: Configure System Event Log (System) | windows-audit-103
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\EventLog\System
    name: "MaxSize"
    data: "1"
    type: dword
  tags: ['configuration']

# No aplicable a maquinas de planta
- name: Configure Windows Audit settings (windows 2012R2)
  include_tasks: windows_2012r2/audit.yml
  when: >
    ansible_facts['os_family']|lower == "windows" and
    (
      ansible_facts['os_name']|lower == "microsoft windows server 2012 r2 standard" or
      ansible_facts['os_name']|lower == "microsoft windows 10 enterprise" or
      ansible_facts['os_name']|lower == "microsoft windows 10 pro"
    ) and
    (audit_enabled|default(True) == True)
  tags: ['configuration']

# No aplicable a maquinas de planta
- name: Configure Windows Audit settings (windows default)
  include_tasks: windows_default/audit.yml
  when: >
    ansible_facts['os_family']|lower == "windows" and
    (
      ansible_facts['os_name']|lower == "microsoft windows server 2016" or
      ansible_facts['os_name']|lower == "microsoft windows server 2019"
    ) and
    (audit_enabled|default(True) == True)
  tags: ['configuration']
