---
- name: IE 64-bit tab | windows-ie-101
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Internet Explorer\Main
    name: "Isolation64Bit"
    data: "1"
    type: dword
  tags: ['configuration']

- name: Run antimalware programs against ActiveX controls | windows-ie-102
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: "270C"
    data: "0"
    type: dword
  tags: ['configuration']
