---
- name: Install sysmon packages from chocolatey repositories
  win_chocolatey:
    name: sysmon 
    state: "{{ (sysmon_required|default(True) == True) | ternary('present', 'absent') }}"
    install_args: '-y'
  notify: initialize_sysmon
  tags: ['install']
