---
- name: Configure sysmon
  block:
    - name: Check if sysmon configuration is downloaded
      win_stat:
        path: '{{ sysmon_config_path }}'
      register: check_sysmon_config_path

    - name: Download sysmon configuration file
      win_get_url:
        url: '{{ sysmon_url }}'
        dest: '{{ sysmon_config_path }}'
      notify: load_sysmon_config 
      when: > 
        check_sysmon_config_path.stat.exists == False and 
        sysmon_required|default(True) == True
  tags: ['configuration']
