---
- name: "CVE-2021-34527 (PrintNightmare) | Ensure 'Devices - Remote connections to print spooler is set to {{ (remote_access_to_print_spooler|default(False) == True) | ternary('Enabled', 'Disabled') }}"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\Windows NT\Printers
     name: "RegisterSpoolerRemoteRpcEndPoint"
     data: "{{ (remote_access_to_print_spooler|default(False) == True) | ternary('1', '2') }}"
     type: dword
  tags: ['configuration']

- name: "CVE-2021-34527 (PrintNightmare) | Ensure 'Devices - Point and Print no elevation on install is set to 'Enabled'"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\Windows NT\Printers\PointAndPrint
     name: "NoElevationOnInstall"
     data: "1"
     type: dword
  tags: ['configuration']

- name: "CVE-2021-34527 (PrintNightmare) | Ensure 'Devices - Point and Print restrict driver installation to administrators"
  win_regedit:
     path: HKLM:\Software\Policies\Microsoft\Windows NT\Printers\PointAndPrint
     name: "RestrictDriverInstallationToAdministrators"
     data: "1"
     type: dword
  tags: ['configuration']
