---
- name: CVE-2021-40444 | Windows registry configuration to disable Active X
  win_regedit:
     path: '{{ reg.path }}'
     name: '{{ reg.name }}'
     data: '{{ reg.data }}' 
     type: '{{ reg.type }}'
  loop:
     - path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\0
       name: 1001
       data: 00000003
       type: dword
     - path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\0
       name: 1004
       data: 00000003
       type: dword
     - path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\1
       name: 1001
       data: 00000003
       type: dword
     - path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\1
       name: 1004
       data: 00000003
       type: dword
     - path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\2
       name: 1001
       data: 00000003
       type: dword
     - path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\2
       name: 1004
       data: 00000003
       type: dword
     - path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
       name: 1001
       data: 00000003
       type: dword
     - path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
       name: 1004
       data: 00000003
       type: dword
  loop_control:
     loop_var: reg
  tags: ['configuration']
