---
- name: Inbound firewall allow rules RDP
  win_firewall_rule:
    name: RDP
    localport: 3389
    action: allow
    direction: in
    protocol: tcp
    remoteip: '{{ rdp_allowed_ip_addresses }}'
    profiles: ['domain','private','public']
    state: present
    enabled: yes
  when:
    - ansible_facts['os_family']|lower == "windows"
  tags: ['configuration']

