---
- name: Configuracion de pam (common-auth) para login consola 2FA con GoogleAuthenticator
  lineinfile:
    path: '/etc/pam.d/common-auth'
    state: present
    regexp: '^auth\s+required pam_google_authenticator\.so'
    line: 'auth required pam_google_authenticator.so nullok'
  tags: ['configuration']

- name: Configuracion de SSH para login 2FA con GoogleAuthenticator
  lineinfile:
    path: '/etc/ssh/sshd_config'
    state: present
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  loop:
    - regexp: '^UsePAM\s'
      line: 'UsePAM yes'
    - regexp: '^ChallengeResponseAuthentication\s+'
      line: 'ChallengeResponseAuthentication yes'
  notify: Restart sshd
  tags: ['configuration']
