---
- name: Configuracion de pam (common-password) para politicas de complejidad de password (pwquality)
  lineinfile:
    path: '/etc/pam.d/common-password'
    state: present
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
    regexp: '^password\s+requisite\s+pam_pwquality.so\s+retry=[0-9]'
    line: 'password     requisite                       pam_pwquality.so retry=3 minlen={{ minlen }} lcredit={{ lcredit }} ucredit={{ ucredit }} dcredit={{ dcredit }} ocredit={{ ocredit }} difok={{ difok }}'
  tags: ['configuration']

- name: Configuracion de pam (common-password) para politicas de complejidad de password (cracklib)
  lineinfile:
    path: '/etc/pam.d/common-password'
    state: present
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
    regexp: '^password\s+requisite\s+pam_cracklib.so\s+retry=[0-9]'
    line: 'password     requisite                       pam_cracklib.so retry=3 minlen={{ minlen }} lcredit={{ lcredit }} ucredit={{ ucredit }} dcredit={{ dcredit }} ocredit={{ ocredit }} difok={{ difok }}'
  tags: ['configuration']
