---
- name: Include variables genericas para la distribucion
  include_vars: '{{ item }}'
  with_first_found:
  - "{{ ansible_distribution }}.yml"
  - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  - default_distro.yml
  tags: ['fail2ban']

- name: Include variables particulares para el host
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ inventory_hostname }}.yml'
    - default_host.yml
  tags: ['fail2ban']

- name: Fail2ban installation
  include_tasks: packages.yml
  tags: ['fail2ban']

- name: Fail2ban type identification and configuration
  block:
    - name: Fail2ban custom facts
      include_tasks: facts.yml
    - name: Fail2ban configuration
      include_tasks: configuration.yml
  tags: ['fail2ban']

- name: Fail2ban services
  include_tasks: services.yml
  tags: ['fail2ban']
