---
- name: Configure IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  tags: ['configuration']

- name: Fix en configuracion para systemd
  lineinfile:
    path: '{{ item.path }}'
    state: present
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - path: '/lib/systemd/system/openvpn.service'
      regexp: '^WorkingDirectory='
      line: 'WorkingDirectory={{ openvpn_conf_dir }}/server'
    - path: '/lib/systemd/system/openvpn@.service'
      regexp: '^CapabilityBoundingSet='
      line: 'CapabilityBoundingSet=CAP_IPC_LOCK CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETGID CAP_SETUID CAP_SYS_CHROOT CAP_DAC_OVERRIDE CAP_AUDIT_WRITE'
  notify: reload_systemd
  tags: ['configuration']

- name: Make sure openvpn log folder exists
  file:
    path: '/var/log/openvpn/'
    mode: '0755'
    owner: 'root'
    group: 'root'
    state: directory
  tags: ['configuration']
