---
- name: APT cache up-to-date
  apt:
    update_cache: yes
  changed_when: false
  when:
    - ansible_facts['os_family']|lower == "debian"
  tags: ['install']

- name: OpenVPN install {{ ansible_os_family }} packages
  package:
    name: '{{ item }}'
  loop: '{{ openvpn_packages }}'
  register: install_result
  until: install_result is success
  retries: 3
  delay: 5
  when:
    - ansible_facts['os_family']|lower == "debian"
  tags: ['install']
