---
- name: Generate auditd configuration file for 32bits processes
  copy:
    dest: '/etc/audit/rules.d/cis-x86.rules'
    owner: root
    group: root
    mode: '0644'
    content: |
      -a always,exit -F arch=b32 -S chmod -F auid>=1000 -F auid!=unset -F key=perm_mod
      -a always,exit -F arch=b32 -S chown -F auid>=1000 -F auid!=unset -F key=perm_mod
      -a always,exit -F arch=b32 -S fchmod -F auid>=1000 -F auid!=unset -F key=perm_mod
      -a always,exit -F arch=b32 -S fchmodat -F auid>=1000 -F auid!=unset -F key=perm_mod
      -a always,exit -F arch=b32 -S fchown -F auid>=1000 -F auid!=unset -F key=perm_mod
      -a always,exit -F arch=b32 -S fchownat -F auid>=1000 -F auid!=unset -F key=perm_mod
      -a always,exit -F arch=b32 -S fremovexattr -F auid>=1000 -F auid!=unset -F key=perm_mod
      -a always,exit -F arch=b32 -S fsetxattr -F auid>=1000 -F auid!=unset -F key=perm_mod
      -a always,exit -F arch=b32 -S lchown -F auid>=1000 -F auid!=unset -F key=perm_mod
      -a always,exit -F arch=b32 -S lremovexattr -F auid>=1000 -F auid!=unset -F key=perm_mod
      -a always,exit -F arch=b32 -S lsetxattr -F auid>=1000 -F auid!=unset -F key=perm_mod
      -a always,exit -F arch=b32 -S removexattr -F auid>=1000 -F auid!=unset -F key=perm_mod
      -a always,exit -F arch=b32 -S setxattr -F auid>=1000 -F auid!=unset -F key=perm_mod
      -a always,exit -F arch=b32 -S rename -F auid>=1000 -F auid!=unset -F key=delete
      -a always,exit -F arch=b32 -S renameat -F auid>=1000 -F auid!=unset -F key=delete
      -a always,exit -F arch=b32 -S unlink -F auid>=1000 -F auid!=unset -F key=delete
      -a always,exit -F arch=b32 -S unlinkat -F auid>=1000 -F auid!=unset -F key=delete
      -a always,exit -F arch=b32 -S creat -F exit=-EACCES -F auid>=1000 -F auid!=unset -F key=access
      -a always,exit -F arch=b32 -S creat -F exit=-EPERM -F auid>=1000 -F auid!=unset -F key=access
      -a always,exit -F arch=b32 -S ftruncate -F exit=-EACCES -F auid>=1000 -F auid!=unset -F key=access
      -a always,exit -F arch=b32 -S ftruncate -F exit=-EPERM -F auid>=1000 -F auid!=unset -F key=access
      -a always,exit -F arch=b32 -S open -F exit=-EACCES -F auid>=1000 -F auid!=unset -F key=access
      -a always,exit -F arch=b32 -S open -F exit=-EPERM -F auid>=1000 -F auid!=unset -F key=access
      -a always,exit -F arch=b32 -S openat -F exit=-EACCES -F auid>=1000 -F auid!=unset -F key=access
      -a always,exit -F arch=b32 -S openat -F exit=-EPERM -F auid>=1000 -F auid!=unset -F key=access
      -a always,exit -F arch=b32 -S truncate -F exit=-EACCES -F auid>=1000 -F auid!=unset -F key=access
      -a always,exit -F arch=b32 -S truncate -F exit=-EPERM -F auid>=1000 -F auid!=unset -F key=access
      -a always,exit -F arch=b32 -S delete_module -F key=modules
      -a always,exit -F arch=b32 -S init_module -F key=modules
      -w /var/log/faillog -p wa -k logins
      -w /var/log/lastlog -p wa -k logins
      -w /var/log/tallylog -p wa -k logins
      -a always,exit -F path=/usr/bin/at -F auid>=1000 -F auid!=unset -F key=privileged
      -a always,exit -F path=/usr/bin/chage -F auid>=1000 -F auid!=unset -F key=privileged
      -a always,exit -F path=/usr/bin/chfn -F perm=x -F auid>=1000 -F auid!=unset -F key=privileged
      -a always,exit -F path=/usr/bin/chsh -F auid>=1000 -F auid!=unset -F key=privileged
      -a always,exit -F path=/usr/bin/crontab -F auid>=1000 -F auid!=unset -F key=privileged
      -a always,exit -F path=/usr/bin/gpasswd -F auid>=1000 -F auid!=unset -F key=privileged
      -w /sbin/insmod -p x -k modules
      -w /sbin/modprobe -p x -k modules
      -a always,exit -F path=/usr/bin/mount -F auid>=1000 -F auid!=unset -F key=privileged
      -a always,exit -F path=/usr/bin/newgidmap -F auid>=1000 -F auid!=unset -F key=privileged
      -a always,exit -F path=/usr/bin/newgrp -F auid>=1000 -F auid!=unset -F key=privileged
      -a always,exit -F path=/usr/bin/newuidmap -F auid>=1000 -F auid!=unset -F key=privileged
      -a always,exit -F path=/usr/sbin/postdrop -F auid>=1000 -F auid!=unset -F key=privileged
      -a always,exit -F path=/usr/sbin/postqueue -F auid>=1000 -F auid!=unset -F key=privileged
      -w /sbin/rmmod -p x -k modules
      -a always,exit -F path=/usr/bin/ssh-agent -F perm=x -F auid>=1000 -F auid!=unset -k privileged-ssh-agent
      -a always,exit -F path=/usr/libexec/openssh/ssh-keysign -F auid>=1000 
      -F auid!=unset -F key=privileged
      -a always,exit -F path=/usr/bin/su -F auid>=1000 -F auid!=unset -F key=privileged
      -a always,exit -F path=/usr/bin/sudo -F auid>=1000 -F auid!=unset -F key=privileged
      -a always,exit -F path=/usr/bin/sudoedit -F auid>=1000 -F auid!=unset -F key=privileged
      -a always,exit -F path=/usr/bin/umount -F auid>=1000 -F auid!=unset -F key=privileged
      -a always,exit -F path=/usr/bin/umount -F auid>=1000 -F auid!=unset -F key=privileged
      -a always,exit -F path=/usr/sbin/unix_chkpwd -F auid>=1000 -F auid!=unset -F key=privileged
      -a always,exit -F arch=b32 -S adjtimex -F key=audit_time_rules
      -a always,exit -F arch=b32 -S clock_settime -F a0=0x0 -F key=time-change
      -a always,exit -F arch=b32 -S settimeofday -F key=audit_time_rules
      -a always,exit -F arch=b32 -S stime -F key=audit_time_rules
      -w /etc/localtime -p wa -k audit_time_rules
      -e 2
      -a always,exit -F arch=b32 -S sethostname,setdomainname -F key=audit_rules_networkconfig_modification
      -w /etc/issue -p wa -k audit_rules_networkconfig_modification
      -w /etc/issue.net -p wa -k audit_rules_networkconfig_modification
      -w /etc/hosts -p wa -k audit_rules_networkconfig_modification
      -w /etc/sysconfig/network -p wa -k audit_rules_networkconfig_modification
      -w /var/run/utmp -p wa -k session
      -w /var/log/btmp -p wa -k session
      -w /var/log/wtmp -p wa -k session
      -a always,exit -F arch=b32 -S execve -C uid!=euid -F euid=0 -k setuid
      -a always,exit -F arch=b32 -S execve -C gid!=egid -F egid=0 -k setgid
      -w /etc/sudoers -p wa -k actions
      -w /etc/sudoers.d/ -p wa -k actions
      -w /etc/group -p wa -k audit_rules_usergroup_modification
      -w /etc/gshadow -p wa -k audit_rules_usergroup_modification
      -w /etc/passwd -p wa -k audit_rules_usergroup_modification
      -w /etc/shadow -p wa -k audit_rules_usergroup_modification
  when: >
    ansible_architecture == 'x86' or
    ansible_architecture == 'x86_64'  
  notify: restart_auditd 
  tags: ['configuration']

- name: Generate auditd configuration file for 64bits processes
  copy:
    dest: '/etc/audit/rules.d/cis-x86_64.rules'
    owner: root
    group: root
    mode: '0644'
    content: |
      -a always,exit -F arch=b64 -S chmod -F auid>=1000 -F auid!=unset -F key=perm_mod
      -a always,exit -F arch=b64 -S chown -F auid>=1000 -F auid!=unset -F key=perm_mod
      -a always,exit -F arch=b64 -S fchmod -F auid>=1000 -F auid!=unset -F key=perm_mod
      -a always,exit -F arch=b64 -S fchmodat -F auid>=1000 -F auid!=unset -F key=perm_mod
      -a always,exit -F arch=b64 -S fchown -F auid>=1000 -F auid!=unset -F key=perm_mod
      -a always,exit -F arch=b64 -S fchownat -F auid>=1000 -F auid!=unset -F key=perm_mod
      -a always,exit -F arch=b64 -S fremovexattr -F auid>=1000 -F auid!=unset -F key=perm_mod
      -a always,exit -F arch=b64 -S fsetxattr -F auid>=1000 -F auid!=unset -F key=perm_mod
      -a always,exit -F arch=b64 -S lchown -F auid>=1000 -F auid!=unset -F key=perm_mod
      -a always,exit -F arch=b64 -S lremovexattr -F auid>=1000 -F auid!=unset -F key=perm_mod
      -a always,exit -F arch=b64 -S lsetxattr -F auid>=1000 -F auid!=unset -F key=perm_mod
      -a always,exit -F arch=b64 -S removexattr -F auid>=1000 -F auid!=unset -F key=perm_mod
      -a always,exit -F arch=b64 -S setxattr -F auid>=1000 -F auid!=unset -F key=perm_mod
      -a always,exit -F arch=b64 -S rename -F auid>=1000 -F auid!=unset -F key=delete
      -a always,exit -F arch=b64 -S renameat -F auid>=1000 -F auid!=unset -F key=delete
      -a always,exit -F arch=b64 -S unlink -F auid>=1000 -F auid!=unset -F key=delete
      -a always,exit -F arch=b64 -S unlinkat -F auid>=1000 -F auid!=unset -F key=delete
      -a always,exit -F arch=b64 -S creat -F exit=-EACCES -F auid>=1000 -F auid!=unset -F key=access
      -a always,exit -F arch=b64 -S creat -F exit=-EPERM -F auid>=1000 -F auid!=unset -F key=access
      -a always,exit -F arch=b64 -S ftruncate -F exit=-EACCES -F auid>=1000 -F auid!=unset -F key=access
      -a always,exit -F arch=b64 -S ftruncate -F exit=-EPERM -F auid>=1000 -F auid!=unset -F key=access
      -a always,exit -F arch=b64 -S open -F exit=-EACCES -F auid>=1000 -F auid!=unset -F key=access
      -a always,exit -F arch=b64 -S open -F exit=-EPERM -F auid>=1000 -F auid!=unset -F key=access
      -a always,exit -F arch=b64 -S openat -F exit=-EACCES -F auid>=1000 -F auid!=unset -F key=access
      -a always,exit -F arch=b64 -S openat -F exit=-EPERM -F auid>=1000 -F auid!=unset -F key=access
      -a always,exit -F arch=b64 -S truncate -F exit=-EACCES -F auid>=1000 -F auid!=unset -F key=access
      -a always,exit -F arch=b64 -S truncate -F exit=-EPERM -F auid>=1000 -F auid!=unset -F key=access
      -a always,exit -F arch=b64 -S delete_module -F key=modules
      -a always,exit -F arch=b64 -S init_module -F key=modules
      -a always,exit -F arch=b64 -S adjtimex -F key=audit_time_rules
      -a always,exit -F arch=b64 -S clock_settime -F a0=0x0 -F key=time-change
      -a always,exit -F arch=b64 -S settimeofday -F key=audit_time_rules
      -a always,exit -F arch=b64 -S stime -F key=audit_time_rules
      -a always,exit -F arch=b64 -S sethostname,setdomainname -F key=audit_rules_networkconfig_modification
      -a always,exit -F arch=b64 -S execve -C uid!=euid -F euid=0 -k setuid
      -a always,exit -F arch=b64 -S execve -C gid!=egid -F egid=0 -k setgid
  when: ansible_architecture == 'x86_64' 
  notify: restart_auditd 
  tags: ['configuration']

- name: Environment variables for easy-rsa
  lineinfile:
    path: '/etc/audit/auditd.conf'
    state: present
    regexp: '^space_left_action'
    line: 'space_left_action = SYSLOG'
  tags: ['configuration']

- name: GRUB2 configuration
  block:
    - name: Make sure the system is GRUB2 compatible
      stat:
        path: '{{ grub2_conf_file }}'
      register: grub2_compatible

    - name: Set boot parameters for audit in GRUB2 configuration
      lineinfile:
        path: '{{ grub2_conf_file }}'
        state: present
        owner: root
        group: root
        mode: "u=rw,g=r,o=r"
        regexp: '^GRUB_CMDLINE_LINUX='
        line: 'GRUB_CMDLINE_LINUX="audit_backlog_limit=8192"'
      when: grub2_compatible.stat.exists == true
      notify: update_grub2
  tags: ['configuration']

