---
- name: Make sure services required by CIS, NIST, DISA standards are running
  systemd:
    name: '{{ item }}'
    enabled: yes
    state: started
  with_items: '{{ services_running }}'
  when:
    - ansible_facts['os_family']|lower == "debian"
  tags: ['services']

- name: Make sure services not required by CIS, NIST, DISA standards are stopped
  systemd:
    name: '{{ item }}'
    enabled: no
    state: stopped
    masked: yes
  with_items: '{{ services_stopped }}'
  when:
    - ansible_facts['os_family']|lower == "debian"
  tags: ['services']

- name: Disable apport.socket service
  block:
    - name: Unit Socket Exists - apport.socket
      command: systemctl list-unit-files apport.socket
      args:
        warn: false
      register: socket_file_exists
      changed_when: false
      ignore_errors: true
      check_mode: false

    - name: Disable socket apport
      systemd:
        name: apport.socket
        enabled: 'no'
        state: stopped
        masked: yes
      when: '"apport.socket" in socket_file_exists.stdout_lines[1]'
  tags: ['services']
