---
- name: Kernel parameters affecting memory and filesystems
  block:
    - name: Ensure sysctl fs.protected_symlinks is set to 1
      sysctl:
        name: fs.protected_symlinks
        value: '1'
        state: present
        reload: true

    - name: Ensure sysctl fs.protected_hardlinks is set to 1
      sysctl:
        name: fs.protected_hardlinks
        value: '1'
        state: present
        reload: true

    - name: Ensure sysctl kernel.randomize_va_space is set to 2
      sysctl:
        name: kernel.randomize_va_space
        value: '2'
        state: present
        reload: true

    - name: Ensure sysctl fs.suid_dumpable is set to 0
      sysctl:
        name: fs.suid_dumpable
        value: '0'
        state: present
        reload: true
    
    - name: Ensure sysctl dev.tty.ldisc_autoload is set to 0
      sysctl:
        name: dev.tty.ldisc_autoload
        value: '0'
        state: present
        reload: true

    - name: Ensure sysctl fs.protected_fifos is set to 2
      sysctl:
        name: fs.protected_fifos
        value: '2'
        state: present
        reload: true

    - name: Ensure sysctl fs.protected_regular is set to 2
      sysctl:
        name: fs.protected_regular
        value: '2'
        state: present
        reload: true

    - name: Ensure sysctl fs.suid_dumpable is set to 0
      sysctl:
        name: fs.suid_dumpable
        value: '0'
        state: present
        reload: true

    - name: Ensure sysctl kernel.core_uses_pid is set to 1
      sysctl:
        name: kernel.core_uses_pid
        value: '1'
        state: present
        reload: true

    - name: Ensure sysctl kernel.ctrl-alt-del is set to 0
      sysctl:
        name: kernel.ctrl-alt-del
        value: '0'
        state: present
        reload: true

    - name: Ensure sysctl kernel.dmesg_restrict is set to 1
      sysctl:
        name: kernel.dmesg_restrict
        value: '1'
        state: present
        reload: true

    - name: Ensure sysctl kernel.kptr_restrict is set to 2
      sysctl:
        name: kernel.kptr_restrict
        value: '2'
        state: present
        reload: true

    #- name: 'Ensure sysctl kernel.modules_disabled is set to 1 (** EXCEPTION ** Kernel modules are required for normal OS operation)'
    #  sysctl:
    #    name: kernel.modules_disabled
    #    value: 1
    #    state: present
    #    reload: true

    - name: Ensure sysctl kernel.unprivileged_bpf_disabled is set to 1
      sysctl:
        name: kernel.unprivileged_bpf_disabled
        value: '1'
        state: present
        reload: true

  tags: ['configuration']

- name: Kernel parameter affecting IPv4 networking
  block:
    - name: Ensure sysctl net.core.bpf_jit_harden is set to 2
      sysctl:
        name: net.core.bpf_jit_harden
        value: '2'
        state: present
        reload: true

    - name: Ensure sysctl net.ipv4.conf.all.log_martians is set to 1
      sysctl:
        name: net.ipv4.conf.all.log_martians
        value: '1'
        state: present
        reload: true

    - name: Ensure sysctl net.ipv4.conf.all.send_redirects is set to 0
      sysctl:
        name: net.ipv4.conf.all.send_redirects
        value: '0'
        state: present
        reload: true

    - name: Ensure sysctl net.ipv4.conf.default.accept_source_route is set to 0
      sysctl:
        name: net.ipv4.conf.default.accept_source_route
        value: '0'
        state: present
        reload: true

    - name: Ensure sysctl net.ipv4.conf.default.log_martians is set to 1
      sysctl:
        name: net.ipv4.conf.default.log_martians
        value: '1'
        state: present
        reload: true

    - name: Disable Accepting ICMP Redirects for All IPv4 Interfaces
      sysctl:
        name: net.ipv4.conf.all.accept_redirects
        value: '0'
        state: present
        reload: true

    - name: Disable Kernel Parameter for Accepting Source-Routed Packets on all IPv4 Interfaces
      sysctl:
        name: net.ipv4.conf.all.accept_source_route
        value: '0'
        state: present
        reload: true

    - name: Enable Kernel Parameter to Use Reverse Path Filtering on all IPv4 Interfaces
      sysctl:
        name: net.ipv4.conf.all.rp_filter
        value: '1'
        state: present
        reload: true

    - name: Disable Kernel Parameter for Accepting Secure ICMP Redirects on all IPv4 Interfaces
      sysctl:
        name: net.ipv4.conf.all.secure_redirects
        value: '0'
        state: present
        reload: true

    - name: Disable Kernel Parameter for Accepting ICMP Redirects by Default on IPv4 Interfaces
      sysctl:
        name: net.ipv4.conf.default.accept_redirects
        value: '0'
        state: present
        reload: true

    - name: Enable Kernel Parameter to Use Reverse Path Filtering on all IPv4 Interfaces by Default
      sysctl:
        name: net.ipv4.conf.default.rp_filter
        value: '1'
        state: present
        reload: true

    - name: Configure Kernel Parameter for Accepting Secure Redirects By Default
      sysctl:
        name: net.ipv4.conf.default.secure_redirects
        value: '0'
        state: present
        reload: true

    - name: Enable Kernel Parameter to Ignore ICMP Broadcast Echo Requests on IPv4 Interfaces
      sysctl:
        name: net.ipv4.icmp_echo_ignore_broadcasts
        value: '1'
        state: present
        reload: true

    - name: Enable Kernel Parameter to Ignore Bogus ICMP Error Responses on IPv4 Interfaces
      sysctl:
        name: net.ipv4.icmp_ignore_bogus_error_responses
        value: '1'
        state: present
        reload: true

    - name: Enable Kernel Parameter to Use TCP Syncookies on IPv4 Interfaces
      sysctl:
        name: net.ipv4.tcp_syncookies
        value: '1'
        state: present
        reload: true

    - name: Disable Kernel Parameter for Sending ICMP Redirects on all IPv4 Interfaces by Default
      sysctl:
        name: net.ipv4.conf.default.send_redirects
        value: '0'
        state: present
        reload: true

    - name: 'Disable Kernel Parameter for IP Forwarding on IPv4 Interfaces (not applicable to routers or switches)'
      sysctl:
        name: net.ipv4.ip_forward
        value: "{{ (ipforwarding_enabled|default(False) == False)  | ternary('0', '1') }}"
        state: present
        reload: true

  tags: ['configuration']

- name: Kernel parameter affecting IPv6 networking
  block:
    - name: Disable Accepting Router Advertisements on All IPv6 Interfaces
      sysctl:
        name: net.ipv6.conf.all.accept_ra
        value: '0'
        state: present
        reload: true

    - name: Disable Accepting ICMP Redirects for All IPv6 Interfaces
      sysctl:
        name: net.ipv6.conf.all.accept_redirects
        value: '0'
        state: present
        reload: true

    - name: Disable Kernel Parameter for Accepting Source-Routed Packets on all IPv6 Interfaces
      sysctl:
        name: net.ipv6.conf.all.accept_source_route
        value: '0'
        state: present
        reload: true

    - name: Disable Kernel Parameter for IPv6 Forwarding
      sysctl:
        name: net.ipv6.conf.all.forwarding
        value: '0'
        state: present
        reload: true

    - name: Disable Accepting Router Advertisements on all IPv6 Interfaces by Default
      sysctl:
        name: net.ipv6.conf.default.accept_ra
        value: '0'
        state: present
        reload: true

    - name: Disable Kernel Parameter for Accepting ICMP Redirects by Default on IPv6 Interfaces
      sysctl:
        name: net.ipv6.conf.default.accept_redirects
        value: '0'
        state: present
        reload: true

    - name: Disable Kernel Parameter for Accepting Source-Routed Packets on IPv6 Interfaces by Default
      sysctl:
        name: net.ipv6.conf.default.accept_source_route
        value: '0'
        state: present
        reload: true

  tags: ['configuration']
