---
- name: Parametrizacion de sysctl
  sysctl:
    sysctl_file: '{{ file_sysctl }}'
    state: present
    reload: yes
    name: '{{ item.name }}'
    value: '{{ item.value }}'
  with_items:
    - name: net.ipv4.icmp_echo_ignore_broadcasts 
      value: '1'
    - name: kernel.sysrq
      value: '0'
    - name: net.ipv4.tcp_timestamps
      value: '0'
    - name: vm.swappiness
      value: '10'
    - name: net.ipv4.tcp_fin_timeout
      value: '5'
    - name: net.core.wmem_max
      value: '16777216'
    - name: net.ipv4.tcp_tw_reuse
      value: '1'
    - name: net.ipv4.tcp_keepalive_time
      value: '120'
    - name: net.core.netdev_max_backlog
      value: '50000'
    - name: net.ipv4.tcp_synack_retries
      value: '3'
    - name: net.ipv4.tcp_retries2
      value: '5'
    - name: net.ipv4.tcp_max_tw_buckets
      value: '2000000'
    - name: net.ipv4.tcp_max_orphans
      value: '60000'
    - name: net.ipv4.tcp_keepalive_intvl
      value: '30'
    - name: net.ipv4.tcp_keepalive_probes
      value: '3'
    - name: net.core.rmem_max
      value: '16777216'
    - name: net.core.wmem_default
      value: '16777216'
    - name: net.ipv4.tcp_sack
      value: '0'
    - name: net.ipv4.tcp_max_syn_backlog
      value: '30000'
    - name: net.ipv4.tcp_dsack
      value: '0'
    - name: net.core.rmem_default
      value: '16777216'
    - name: net.core.optmem_max
      value: '40960'
    - name: net.ipv4.tcp_rmem
      value: '4096 87380 16777216'
    - name: net.ipv4.tcp_wmem
      value: '4096 87380 16777216'
  tags: ['configuration']
