---
- name: Make sure TeamViewer service is stopped as a default rule
  win_service:
     name: TeamViewer
     state: "{{ teamviewer_required|default(False) | ternary('started', 'stopped') }}"
  when:
    - ansible_facts['os_family']|lower == "windows"
  tags: ['services']

