---
- name: "LOW | V-1075 | PATCH | The shutdown option will not be available from the logon dialog box."
  win_regedit:
      key: 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System'
      value: ShutdownWithoutLogon
      data: 0
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-1090 | PATCH | Caching of logon credentials must be limited."
  win_regedit:
      key: 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon'
      value: CachedLogonsCount
      data: 0
  tags: ['cat3']

- name: "LOW | V-1151 | PATCH | The print driver installation privilege will be restricted to administrators."
  win_regedit:
      key: 'HKLM:\System\CurrentControlSet\Control\Print\Providers\LanMan Print Services\Servers'
      value: AddPrinterDrivers
      data: 1
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-1158 | PATCH | The Recovery Console SET command must be disabled."
  win_regedit:
      key: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Setup\RecoveryConsole'
      value: SetCommand
      data: 0
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-1165 | PATCH | The computer account password will not be prevented from being reset."
  win_regedit:
      key: 'HKLM:\System\CurrentControlSet\Services\Netlogon\Parameters'
      value: DisablePasswordChange
      data: 0
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-1172 | PATCH | Users will be warned in advance that their passwords will expire."
  win_regedit:
      key: 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon'
      value: PasswordExpiryWarning
      data: 7
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-1173 | PATCH | The default permissions of Global system objects will be increased."
  win_regedit:
      key: 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon'
      value: ProtectionMode
      data: 1
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-1174 | PATCH | The amount of idle time required before suspending a session must be properly set."
  win_regedit:
      key: 'HKLM:\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters'
      value: autodisconnect
      data: 0x0000000f
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-3373 | PATCH | The maximum age for machine account passwords will be set to requirements."
  win_regedit:
      key: 'HKLM:\System\CurrentControlSet\Services\Netlogon\Parameters'
      value: MaximumPasswordAge
      data: 30
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-3472 | AUDIT | If the time service is configured, it will use an authorized time server."
  win_command: 'reg query HKLM\Software\Policies\Microsoft\W32time\Parameters /v Type'
  register: time_type_audit
  check_mode: no
  changed_when: no
  failed_when: >
     time_type_audit.stderr != "" and
     '"reg_not_found" not in time_type_audit.stderr'
  tags: ['cat3']

- name: "LOW | V-3472 | AUDIT | If the time service is configured, it will use an authorized time server."
  win_command: 'reg query HKLM\Software\Policies\Microsoft\W32time\Parameters /v NTPServer'
  register: NTP_server_audit
  check_mode: no
  changed_when: no
  failed_when: >
     NTP_server_audit.stderr != "" and
     '"reg_not_found" not in NTP_server_audit.stderr'
  tags: ['cat3']

- name: "LOW | V-4110 | PATCH | The system will be configured to prevent IP source routing."
  win_regedit:
      key: 'HKLM:\System\CurrentControlSet\Services\Tcpip\Parameters'
      value: DisableIPSourceRouting
      data: 2
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-4112 | PATCH | The system will be configured to disable the Internet Router Discover Protocol (IRDP)."
  win_regedit:
      key: 'HKLM:\System\CurrentControlSet\Services\Tcpip\Parameters'
      value: PerformRouterDiscovery
      data: 0
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-4113 | PATCH | The system will be configured to limit how often keep-alive packets are sent."
  win_regedit:
      key: 'HKLM:\System\CurrentControlSet\Services\Tcpip\Parameters'
      value: KeepAliveTime
      data: 300000
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-4116 | PATCH | The system must be configured to ignore NetBIOS name release requests except from WINS servers."
  win_regedit:
      key: 'HKLM:\SYSTEM\CurrentControlSet\Services\Netbt\Parameters'
      value: NoNameReleaseOnDemand
      data: 1
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-4438 | PATCH | The system must limit how many times unacknowledged TCP data is retransmitted."
  win_regedit:
      key: 'HKLM:\System\CurrentControlSet\Services\Tcpip\Parameters'
      value: TcpMaxDataRetransmissions
      data: 3
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-4442 | PATCH | The system will be configured to have password protection take effect within a limited time frame when the screen saver becomes active."
  win_regedit:
      key: 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon'
      value: ScreenSaverGracePeriod
      data: 0
      datatype: string
  tags: ['cat3']

- name: "LOW | V-4445 | AUDIT | Optional Subsystems will not be permitted to operate on the system."
  win_command: 'reg query "HKLM\System\CurrentControlSet\Control\Session Manager\Subsystems" /v Optional'
  register: optional_subsystem_audit
  check_mode: no
  changed_when: no
  ignore_errors: yes
  tags: ['cat3']

- name: "LOW | V-4445 | PATCH | Optional Subsystems will not be permitted to operate on the system."
  win_command: 'reg add "HKLM\System\CurrentControlSet\Control\Session Manager\Subsystems" /v Optional /t REG_MULTI_SZ /'
  when: > 
     optional_subsystem_audit.stderr != "" and
     '"reg_not_found" not in optional_subsystem_audit.stderr'
  tags: ['cat3']

- name: "LOW | V-11806 | PATCH | The system will be configured to prevent the display of the last user name on the logon screen."
  win_regedit:
      key: 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System'
      value: DontDisplayLastUserName
      data: 1
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-15672 | PATCH | Event Viewer Events.asp links will be turned off."
  win_regedit:
      key: 'HKLM:\Software\Policies\Microsoft\EventViewer'
      value: MicrosoftEventVwrDisableLinks
      data: 1
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-15680 | PATCH | The classic logon screen must be required for user logons."
  win_regedit:
      key: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'
      value: LogonType
      data: 0
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-15686 | PATCH | Non-administrators will be prevented from applying vendor signed updates."
  win_regedit:
      key: 'HKLM:\Software\Policies\Microsoft\Windows\Installer'
      value: DisableLUAPatching
      data: 1
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-15687 | PATCH | Users will not be presented with Privacy and Installation options on first use of Windows Media Player."
  win_regedit:
      key: 'HKLM:\Software\Policies\Microsoft\WindowsMediaPlayer'
      value: GroupPrivacyAcceptance
      data: 1
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-15701 | PATCH | A system restore point will be created when a new device driver is installed."
  win_regedit:
      key: 'HKLM:\Software\Policies\Microsoft\Windows\DeviceInstall\Settings'
      value: DisableSystemRestore
      data: 0
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-15702 | PATCH | An Error Report will not be sent when a generic device driver is installed."
  win_regedit:
      key: 'HKLM:\Software\Policies\Microsoft\Windows\DeviceInstall\Settings'
      value: DisableSendGenericDriverNotFoundToWER
      data: 1
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-15703 | PATCH | Users will not be prompted to search Windows Update for device drivers."
  win_regedit:
      key: 'HKLM:\Software\Policies\Microsoft\Windows\DriverSearching'
      value: DontPromptForWindowsUpdate
      data: 1
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-15704 | PATCH | Errors in handwriting recognition on Tablet PCs will not be reported to Microsoft."
  win_regedit:
      key: 'HKLM:\Software\Policies\Microsoft\Windows\HandwritingErrorReports'
      value: PreventHandwritingErrorReports
      data: 1
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-15707 | PATCH | Remote Assistance log files will be generated."
  win_regedit:
      key: 'HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services'
      value: LoggingEnabled
      data: 1
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-15718 | PATCH | Windows Explorer heap termination on corruption will be disabled."
  win_regedit:
      key: 'HKLM:\Software\Policies\Microsoft\Windows\Explorer'
      value: NoHeapTerminationOnCorruption
      data: 0
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-15719 | PATCH | Users must be notified if the logon server was inaccessible and cached credentials were used."
  win_regedit:
      key: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'
      value: ReportControllerMissing
      data: 1
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-16005 | PATCH | The system will be configured to remove the Disconnect option from the Shut Down Windows dialog box on the Remote Desktop Client. (Remote Desktop Services Role)"
  win_regedit:
      key: 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer'
      value: NoDisconnect
      data: 1
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-21955 | PATCH | IPv6 source routing will be configured to highest protection."
  win_regedit:
      key: 'HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters'
      value: DisableIPSourceRouting
      data: 2
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-21956 | PATCH | IPv6 TCP data retransmissions must be configured to prevent resources from becoming exhausted."
  win_regedit:
      key: 'HKLM:\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters'
      value: TcpMaxDataRetransmissions
      data: 3
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-21960 | PATCH | Domain users will be required to elevate when setting a network's location."
  win_regedit:
      key: 'HKLM:\Software\Policies\Microsoft\Windows\Network Connections'
      value: NC_StdDomainUserSetLocation
      data: 1
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-21961 | PATCH | All Direct Access traffic will be routed through the internal network."
  win_regedit:
      key: 'HKLM:\Software\Policies\Microsoft\Windows\TCPIP\v6Transition'
      value: Force_Tunneling
      data: 1
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-21963 | PATCH | Windows Update will be prevented from searching for point and print drivers."
  win_regedit:
      key: 'HKLM:\Software\Policies\Microsoft\Windows NT\Printers'
      value: DoNotInstallCompatibleDriverFromWindowsUpdate
      data: 1
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-21964 | PATCH | Device metadata retrieval from the Internet must be prevented."
  win_regedit:
      key: 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\Device Metadata'
      value: PreventDeviceMetadataFromNetwork
      data: 1
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-21965 | PATCH | Device driver searches using Windows Update will be prevented."
  win_regedit:
      key: 'HKLM:\Software\Policies\Microsoft\Windows\DriverSearching'
      value: SearchOrderConfig
      data: 0
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-21967 | PATCH | Microsoft Support Diagnostic Tool (MSDT) interactive communication with Microsoft will be prevented."
  win_regedit:
      key: 'HKLM:\Software\Policies\Microsoft\Windows\ScriptedDiagnosticsProvider\Policy'
      value: DisableQueryRemoteServer
      data: 0
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-21969 | PATCH | Access to Windows Online Troubleshooting Service (WOTS) will be prevented."
  win_regedit:
      key: 'HKLM:\Software\Policies\Microsoft\Windows\ScriptedDiagnosticsProvider\Policy'
      value: EnableQueryRemoteServer
      data: 0
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-21970 | PATCH | Responsiveness events will be prevented from being aggregated and sent to Microsoft."
  win_regedit:
      key: 'HKLM:\Software\Policies\Microsoft\Windows\WDI\{9c5a40da-b965-4fc3-8781-88dd50a6299d}'
      value: ScenarioExecutionEnabled
      data: 0
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-21971 | PATCH | The Application Compatibility Program Inventory will be prevented from collecting data and sending the information to Microsoft."
  win_regedit:
      key: 'HKLM:\Software\Policies\Microsoft\Windows\AppCompat'
      value: DisableInventory
      data: 1
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-26475 | PATCH | Unauthorized accounts must not have the Bypass traverse checking user right."
  win_user_right:
      name: SeChangeNotifyPrivilege
      users: ['Usuarios autentificados','Servicio local','Servicio de red','Administradores']
  tags: ['cat3']

- name: "LOW | V-26477 | PATCH | Unauthorized accounts must not have the Change the time zone user right."
  win_user_right:
      name: SeTimeZonePrivilege
      users: ['Servicio local','Administradores']
  tags: ['cat3']

- name: "LOW | V-28504 | PATCH | Windows will be prevented from sending an error report when a device driver requests additional software during installation."
  win_regedit:
      key: 'HKLM:\Software\Policies\Microsoft\Windows\DeviceInstall\Settings'
      value: DisableSendRequestAdditionalSoftwareToWER
      data: 1
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-36673 | PATCH | IP stateless autoconfiguration limits state must be enabled."
  win_regedit:
      key: 'HKLM:\System\CurrentControlSet\Services\Tcpip\Parameters\'
      value: EnableIPAutoConfigurationLimits
      data: 1
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-36677 | PATCH | Optional component installation and component repair must be prevented from using Windows Update."
  win_regedit:
      key: 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Servicing\'
      value: UseWindowsUpdate
      data: 2
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-36678 | PATCH | Device driver updates must only search managed servers, not Windows Update."
  win_regedit:
      key: 'HKLM:\Software\Policies\Microsoft\Windows\DriverSearching\'
      value: DriverServerSelection
      data: 1
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-36696 | PATCH | The detection of compatibility issues for applications and drivers must be turned off."
  win_regedit:
      key: 'HKLM:\Software\Policies\Microsoft\Windows\AppCompat\'
      value: DisablePcaUI
      data: 0
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-36697 | PATCH | Trusted app installation must be enabled to allow for signed enterprise line of business apps."
  win_regedit:
      key: 'HKLM:\Software\Policies\Microsoft\Windows\Appx\'
      value: AllowAllTrustedApps
      data: 1
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-36707 | PATCH | The Windows SmartScreen must be turned off."
  win_regedit:
      key: 'HKLM:\Software\Policies\Microsoft\Windows\System\'
      value: EnableSmartScreen
      data: 0
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-36710 | PATCH | Automatic download of updates from the Windows Store must be turned off."
  win_regedit:
      key: 'HKLM:\SOFTWARE\Policies\Microsoft\WindowsStore\'
      value: AutoDownload
      data: 0x00000002
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-36774 | PATCH | A screen saver must be defined."
  win_regedit:
      key: 'HKCU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop\'
      value: SCRNSAVE.EXE
      data: scrnsave.scr
      datatype: string
  when: >
      ansible_virtualization_role != "guest" and
      ansible_system_vendor != "QEMU"
  tags: ['cat3']

- name: "LOW | V-36775 | PATCH | Changing the screen saver must be prevented."
  win_regedit:
      key: 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\System\'
      value: NoDispScrSavPage
      data: 1
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-36776 | PATCH | Notifications from Windows Push Network Service must be turned off."
  win_regedit:
      key: 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\System\'
      value: NoCloudApplicationNotification
      data: 1
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-36777 | PATCH | Toast notifications to the lock screen must be turned off."
  win_regedit:
      key: 'HKCU:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\PushNotifications\'
      value: NoToastApplicationNotificationOnLockScreen
      data: 1
      datatype: dword
  tags: ['cat3']

- name: "LOW | V-43241 | PATCH | The setting to allow Microsoft accounts to be optional for modern style apps must be enabled (Windows 2012 R2)."
  win_regedit:
      key: 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'
      value: MSAOptional
      data: 1
      datatype: dword
  tags: ['cat3']

